TOP=../..

include $(TOP)/configure/CONFIG

TEMPLATES_DIR = makeBaseApp

TEMPLATES += top/Makefile

## ================================================
## Application TOP needs Documentation
## ================================================
TEMPLATES += top/README
TEMPLATES += top/RELEASE_NOTES
TEMPLATES += top/RELEASE_SITE
TEMPLATES += top/edm-_IOC_.cmd

## =================================================

TEMPLATES += top/_APPNAME_Screens/_APPNAME_.edl

TEMPLATES += top/autosave/autosave.req
TEMPLATES += top/autosave/autosave_evr.req

TEMPLATES += top/archive/iocAdmin.req
TEMPLATES += top/archive/_IOC_.substitutions

TEMPLATES += top/configure/CONFIG
TEMPLATES += top/configure/CONFIG_SITE
TEMPLATES += top/configure/Makefile
TEMPLATES += top/configure/RELEASE
TEMPLATES += top/configure/RULES
TEMPLATES += top/configure/RULES.ioc
TEMPLATES += top/configure/RULES.copy
TEMPLATES += top/configure/RULES_DIRS
TEMPLATES += top/configure/RULES_TOP

## =================================================

TEMPLATES += top/supportApp/Makefile
TEMPLATES += top/supportApp/Db/Makefile
TEMPLATES += top/supportApp/src/Makefile
TEMPLATES += top/supportApp/src/_APPNAME_.dbd

TEMPLATES += top/iocApp/Makefile
TEMPLATES += top/iocApp/Db/Makefile
TEMPLATES += top/iocApp/src/Makefile
TEMPLATES += top/iocApp/src/_APPNAME_Main.cpp
TEMPLATES += top/iocApp/src/sncExample.stt

TEMPLATES += top/exampleApp/Makefile
TEMPLATES += top/exampleApp/Db/Makefile
TEMPLATES += top/exampleApp/Db/dbExample1.db
TEMPLATES += top/exampleApp/Db/dbExample2.db
TEMPLATES += top/exampleApp/Db/dbSubExample.db
TEMPLATES += top/exampleApp/Db/user.substitutions
TEMPLATES += top/exampleApp/Db/userHost.substitutions
TEMPLATES += top/exampleApp/src/Makefile
TEMPLATES += top/exampleApp/src/xxxRecord.dbd
TEMPLATES += top/exampleApp/src/xxxRecord.c
TEMPLATES += top/exampleApp/src/devXxxSoft.c
TEMPLATES += top/exampleApp/src/xxxSupport.dbd
TEMPLATES += top/exampleApp/src/sncExample.stt
TEMPLATES += top/exampleApp/src/sncProgram.st
TEMPLATES += top/exampleApp/src/sncExample.dbd
TEMPLATES += top/exampleApp/src/dbSubExample.c
TEMPLATES += top/exampleApp/src/dbSubExample.dbd
TEMPLATES += top/exampleApp/src/_APPNAME_Main.cpp
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.c
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.dbd

TEMPLATES += top/exampleBoot/Makefile

TEMPLATES += top/exampleBoot/nfsCommands@vxWorks
TEMPLATES += top/exampleBoot/nfsCommands@vxWorks6

TEMPLATES += top/exampleBoot/nfsCommands@RTEMS
TEMPLATES += top/exampleBoot/ioc/Makefile@Common

TEMPLATES += top/exampleBoot/ioc/Makefile@vxWorks
TEMPLATES += top/exampleBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/exampleBoot/ioc/st.cmd@Common

TEMPLATES += top/exampleBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/exampleBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/exampleBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/exampleBoot/ioc/README@Common

TEMPLATES += top/exampleBoot/ioc/README@vxWorks
TEMPLATES += top/exampleBoot/ioc/README@vxWorks6

TEMPLATES += top/caClientApp/Makefile
TEMPLATES += top/caClientApp/caExample.c
TEMPLATES += top/caClientApp/caMonitor.c

TEMPLATES += top/caServerApp/Makefile
TEMPLATES += top/caServerApp/README
TEMPLATES += top/caServerApp/exAsyncPV.cc
TEMPLATES += top/caServerApp/exChannel.cc
TEMPLATES += top/caServerApp/exPV.cc
TEMPLATES += top/caServerApp/exScalarPV.cc
TEMPLATES += top/caServerApp/exServer.cc
TEMPLATES += top/caServerApp/exServer.h
TEMPLATES += top/caServerApp/exVectorPV.cc
TEMPLATES += top/caServerApp/main.cc
TEMPLATES += top/caServerApp/test.adl
TEMPLATES += top/caServerApp/vxEntry.cc

TEMPLATES += top/iocBoot/Makefile

TEMPLATES += top/iocBoot/nfsCommands@vxWorks
TEMPLATES += top/iocBoot/nfsCommands@vxWorks6

TEMPLATES += top/iocBoot/nfsCommands@RTEMS
TEMPLATES += top/iocBoot/ioc/Makefile@Common

TEMPLATES += top/iocBoot/ioc/Makefile@vxWorks
TEMPLATES += top/iocBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/iocBoot/ioc/st.cmd@Common
TEMPLATES += top/iocBoot/ioc/st.cmd@Cross

TEMPLATES += top/iocBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/iocBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/iocBoot/ioc/st.cmd@RTEMS


## ============================================
## LCLS Style Templates (Added by ELW)
## ============================================
TEMPLATES += top/lclsApp/Makefile
TEMPLATES += top/lclsApp/Db/Makefile
TEMPLATES += top/lclsApp/Db/dbExample1.db
TEMPLATES += top/lclsApp/Db/dbExample2.db
TEMPLATES += top/lclsApp/Db/dbSubExample.db
TEMPLATES += top/lclsApp/src/Makefile
TEMPLATES += top/lclsApp/src/xxxRecord.dbd
TEMPLATES += top/lclsApp/src/xxxRecord.c
TEMPLATES += top/lclsApp/src/devXxxSoft.c
TEMPLATES += top/lclsApp/src/xxxSupport.dbd
TEMPLATES += top/lclsApp/src/sncExample.stt
TEMPLATES += top/lclsApp/src/sncProgram.st
TEMPLATES += top/lclsApp/src/sncExample.dbd
TEMPLATES += top/lclsApp/src/dbSubExample.c
TEMPLATES += top/lclsApp/src/dbSubExample.dbd
TEMPLATES += top/lclsApp/src/_APPNAME_Main.cpp
TEMPLATES += top/lclsApp/src/_APPNAME_Hello.c
TEMPLATES += top/lclsApp/src/_APPNAME_Hello.dbd

TEMPLATES += top/lclsApp/srcDisplay/Makefile
TEMPLATES += top/lclsApp/srcDisplay/example.edl

TEMPLATES += top/lclsApp/srcRestore/Makefile
TEMPLATES += top/lclsApp/srcRestore/example.cwConfig

TEMPLATES += top/lclsBoot/Makefile

TEMPLATES += top/lclsBoot/nfsCommands@vxWorks
TEMPLATES += top/lclsBoot/nfsCommands@vxWorks6

TEMPLATES += top/lclsBoot/nfsCommands@RTEMS
TEMPLATES += top/lclsBoot/ioc/Makefile@Common

TEMPLATES += top/lclsBoot/ioc/Makefile@vxWorks
TEMPLATES += top/lclsBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/lclsBoot/ioc/st.cmd@Common
TEMPLATES += top/lclsBoot/ioc/st.cmd@Cross

TEMPLATES += top/lclsBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/lclsBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/lclsBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/lclsBoot/ioc/README@Common

TEMPLATES += top/lclsBoot/ioc/README@vxWorks
TEMPLATES += top/lclsBoot/ioc/README@vxWorks6

## ==========================================
## End Changes needed for LCLS ==============
## ==========================================

######################################################################
# PCDS templates: 'pcdsDemoApp' and 'pcdsDemoBoot'.
# Author: Jason Tiller
######################################################################

# pcdsDemoApp - based on lclsApp.  Also includes a 'srcProtocol' directory
# for managing streamDevice's protocol files.

TEMPLATES += top/pcdsDemoApp/Makefile
TEMPLATES += top/pcdsDemoApp/Db/Makefile
TEMPLATES += top/pcdsDemoApp/Db/dbExample1.db
TEMPLATES += top/pcdsDemoApp/Db/dbExample2.db
TEMPLATES += top/pcdsDemoApp/Db/dbSubExample.db
TEMPLATES += top/pcdsDemoApp/src/Makefile
TEMPLATES += top/pcdsDemoApp/src/xxxRecord.dbd
TEMPLATES += top/pcdsDemoApp/src/xxxRecord.c
TEMPLATES += top/pcdsDemoApp/src/devXxxSoft.c
TEMPLATES += top/pcdsDemoApp/src/xxxSupport.dbd
TEMPLATES += top/pcdsDemoApp/src/sncExample.stt
TEMPLATES += top/pcdsDemoApp/src/sncProgram.st
TEMPLATES += top/pcdsDemoApp/src/sncExample.dbd
TEMPLATES += top/pcdsDemoApp/src/dbSubExample.c
TEMPLATES += top/pcdsDemoApp/src/dbSubExample.dbd
TEMPLATES += top/pcdsDemoApp/src/_APPNAME_Main.cpp
TEMPLATES += top/pcdsDemoApp/src/_APPNAME_Hello.c
TEMPLATES += top/pcdsDemoApp/src/_APPNAME_Hello.dbd

TEMPLATES += top/pcdsDemoApp/srcDisplay/Makefile
TEMPLATES += top/pcdsDemoApp/srcDisplay/example.edl

TEMPLATES += top/pcdsDemoApp/srcProtocol/Makefile
TEMPLATES += top/pcdsDemoApp/srcProtocol/example.proto

# pcdsDemoBoot - based on lclsBoot.  Will copy 'iocBoot' (and st.cmd!)
# into INSTALL_LOCATION if you aren't building in your development
# directory.

TEMPLATES += top/pcdsDemoBoot/Makefile

TEMPLATES += top/pcdsDemoBoot/nfsCommands@vxWorks
TEMPLATES += top/pcdsDemoBoot/nfsCommands@vxWorks6

TEMPLATES += top/pcdsDemoBoot/nfsCommands@RTEMS
TEMPLATES += top/pcdsDemoBoot/ioc/Makefile@Common

TEMPLATES += top/pcdsDemoBoot/ioc/Makefile@vxWorks
TEMPLATES += top/pcdsDemoBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/pcdsDemoBoot/ioc/st.cmd@Common
TEMPLATES += top/pcdsDemoBoot/ioc/st.cmd@Cross

TEMPLATES += top/pcdsDemoBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/pcdsDemoBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/pcdsDemoBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/pcdsDemoBoot/ioc/README@Common

TEMPLATES += top/pcdsDemoBoot/ioc/README@vxWorks
TEMPLATES += top/pcdsDemoBoot/ioc/README@vxWorks6

######################################################################
# PCDS templates: 'pcdsIocApp' and 'pcdsIocBoot'.
# Author: Bruce Hill
######################################################################

# pcdsIocApp - Basic pcds IOC including autosave and iocAdmin

TEMPLATES += top/pcdsIocApp/Replace.pl
TEMPLATES += top/pcdsIocApp/Makefile
TEMPLATES += top/pcdsIocApp/Db/Makefile
TEMPLATES += top/pcdsIocApp/Db/iocAdmin.substitutions
TEMPLATES += top/pcdsIocApp/src/Makefile
TEMPLATES += top/pcdsIocApp/src/_APPNAME_Main.cpp
TEMPLATES += top/pcdsIocApp/configure/RELEASE

# pcdsIocBoot - based on lclsBoot.  Will copy 'iocBoot' (and st.cmd!)
# into INSTALL_LOCATION if you aren't building in your development
# directory.

TEMPLATES += top/pcdsIocBoot/Makefile

TEMPLATES += top/pcdsIocBoot/ioc/Makefile@Common

TEMPLATES += top/pcdsIocBoot/ioc/st.cmd@Common
TEMPLATES += top/pcdsIocBoot/ioc/st.cmd@RTEMS

TEMPLATES += top/pcdsIocBoot/ioc/startup.cmd@Common
TEMPLATES += top/pcdsIocBoot/ioc/startup.cmd@RTEMS

TEMPLATES += top/pcdsIocBoot/ioc/README@Common


######################################################################
# PCDS templates: 'pcdsEvrApp' and 'pcdsEvrBoot'.
# Author: Bruce Hill
######################################################################

# pcdsEvrApp - Basic pcds IOC including autosave and iocAdmin

TEMPLATES += top/pcdsEvrApp/Makefile
TEMPLATES += top/pcdsEvrApp/Db/Makefile
TEMPLATES += top/pcdsEvrApp/Db/iocAdmin.substitutions
TEMPLATES += top/pcdsEvrApp/Db/evr.substitutions
TEMPLATES += top/pcdsEvrApp/src/Makefile
TEMPLATES += top/pcdsEvrApp/src/_APPNAME_Main.cpp
TEMPLATES += top/pcdsEvrApp/configure/RELEASE
#TEMPLATES += top/pcdsEvrApp/autosave/Makefile
#TEMPLATES += top/pcdsEvrApp/autosave/_APPNAME_.substitutions
#TEMPLATES += top/pcdsEvrApp/autosave/autosave_evr.req

# pcdsEvrBoot - based on lclsBoot.  Will copy 'iocBoot' (and st.cmd!)
# into INSTALL_LOCATION if you aren't building in your development
# directory.

TEMPLATES += top/pcdsEvrBoot/Makefile

TEMPLATES += top/pcdsEvrBoot/ioc/Makefile@Common

TEMPLATES += top/pcdsEvrBoot/ioc/st.cmd@Common
TEMPLATES += top/pcdsEvrBoot/ioc/st.cmd@RTEMS

TEMPLATES += top/pcdsEvrBoot/ioc/startup.cmd@Common
TEMPLATES += top/pcdsEvrBoot/ioc/startup.cmd@RTEMS

TEMPLATES += top/pcdsEvrBoot/ioc/README@Common

######################################################################
# End of PCDS additions
######################################################################

SCRIPTS_HOST += makeBaseApp.pl

include $(TOP)/configure/RULES

